# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nir Yechiel's Blog
author: Nir Yechiel
# email: n.yechiel@gmail.com # Removed to prevent spam - contact via social links
description: >- # this means to ignore newlines until "baseurl:"
  Random thoughts on product engineering, technology, people, and where they intersect.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://nyechiel.com # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:year/:month/:day/:title/
show_excerpts: true
header_pages:
  - index.md
  - blog/index.md
  - about.md
twitter_username: nyechiel
github_username: nyechiel
linkedin_username: nyechiel
rss: rss
social:
  name: Nir Yechiel
  links:
    - https://twitter.com/nyechiel
    - https://www.linkedin.com/in/nyechiel
    - https://github.com/nyechiel
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

# Feed configuration
feed:
  posts_limit: 50
  excerpt_only: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
